#+title: Mathematical Foundations for Computer Science

* Number Systems
** Natural Numbers

The set of Natural numbers $\mathbb{N}$, is the infinite set of all non-negative Integers, including $0$.

The /natural numbers/ are those used with the purpose of counting or ordering. In the sentence /"There are 7 continents."/ the natural number 7 is used to count items, it is used as a /cardinal/. In the sentence /"Europe is the sixth largest continent by area."/ the natural number *six* is used to express Europe's position in amongst some items, it is used as an /ordinal/.

Depending on context, the set of natural numbers may or may not include zero. In computer science, zero is an important element of the set of natural numbers. When counting, it is obviously possible to have $0, 1, 2, 3, \ldots$ items, this is not confusing. Determining the ordinal position (/index/) of an item in a collection is more ambiguous. Considering the list $[5,8,4,6]$:

- The index of an item could be expressed as the number of other elements ahead of it, including itself. This is called /inclusive/ indexing. This would make $4$ the /inclusive third/ element in this list. In spoken English, this is the convention, though this may not be the case in other languages or cultures.

- Alternatively, the index of the same item could be simply expressed by the number of items ahead of it, excluding itself. This is called /exclusive/ indexing. This would make the element $4$ the /exclusive second/ element in the same list. The element $5$ would be called the /zeroth/ element of this list. In computing, this is generally the convention.
  
*** Natural Number Notation

Every natural number $n$ has a /successor/ $\textbf{S}n$. Any natural number can be expressed as in terms of this operation and the natural number $0$. For example $3$ can be represented as $\textbf{SSS}0$. This is called /unary/ notation. Unary notation is impractical for writing large natural numbers.

In place of mathematical unary notation, /positional/ notation (sometimes called place-value notation) is used almost exclusively. Positional systems have a /base/ or /radix/, which is a natural number greater than one. With a base of $b$, the first $b$ natural numbers including zero ($0$ to $b -1$) are represented with a single symbol or digit. All larger natural numbers are written by multiplying the value of one of these $b$ digits by its position. As a digit is moved or added to the left, its value is multiplied by its position. The position of a digit $a$ in a given numeral is zero indexed from the right to left.  

\[a_{n}a_{n-1}a_{n-2} \ldots a_{0}\]

The value of a number written in positional notation is the sum of the digits multiplied by the radix raised to the power of its position.

\[ a_{n}b^{n} + a_{n-1}b^{n-1} + a_{n-2}b^{n-2} + \ldots + a_{0}b^{0} \]

\[\sum^{n}_{k = 0}a_{k}b^{k}\]

The /decimal/ system (base 10) is most often used and assumed to be the default base, that is unless another base is explicitly specified. This is often done with a subscript after the representation of a number. $11$ is assumed to be the natural number eleven, written in decimal, rather than three written in binary. $11_2$ is unmistakably binary, but this specificity isn't always necessary.

#+include: "./tables/positional_notation_1.org"

** Algebraic Structures

An /algebraic structure/ consists of a non-empty set $A$ (know as the underlying set, carrier set or domain), a collection of operations on $A$ and a finite set of axioms for operations on $A$ to satisfy.

*** Field

A /field/ is one such algebraic structure for which addition, subtraction, multiplication and division are defined. A field is a set $F$ equipped with two binary operations: addition and multiplication. The result of the addition of two elements $a$ and $b$ is called their sum, written $a+b$. The result of the multiplication of $a$ and $b$ is called their product, written $ab$, $a \cdot b$ or $a \times b$. Fields operations have some axioms.

- Associativity of addition: $a + (b + c) = (a + b) + c$.
- Associativity of multiplication: $a \cdot (b \cdot c) = (a \cdot b) \cdot c$.
- Commutativity of addition: $a + b = b + a$.
- Commutativity of multiplication: $a \cdot b = b \cdot a$.
- Additive identity element $0 \in F$: $a + 0 = a$. 
- Multiplicative identity element $1 \in F$: $a \cdot 1 = a$.
- Additive inverse of all elements $a$ is $-a$: $a + (-a) = 0$.
- Multiplicative inverse of all non-zero elements $a$ is $a^{-1}$: $a \cdot {a^{-1}} = 1$.
- Distributivity of multiplication over addition: $a \cdot (b + c) = (a \cdot b) + (a \cdot c)$.

The additive inverse of $a$ is written $-a$. The multiplicative inverse of $a \neq 0$ is written $a^{-1}$. The /"inverse operations"/ of subtraction $a-b$ and division $a/b$ can be defined in terms of the inverse element of $a$ and $b$.

\[a-b \stackrel{\text{def}}{=} a + (-b)\]
\[a/b \stackrel{\text{def}}{=} a \cdot (b^{-1})\]

A field is similar to a /commutative ring/ with the addition of the multiplicative inverse for all non-zero elements of $F$. The rational numbers $\mathbb{Q}$ and real numbers $\mathbb{R}$ form a field.

*** Ring & Commutative Ring

A /ring/ is an algebraic structure similar to a field, but without the need for multiplication to be commutative and the need for elements to have a multiplicative inverse. In most cases a ring is said to contain the multiplicative identity element axiom, the list of ring axioms being:

- Associativity of addition: $a + (b + c) = (a + b) + c$.
- Associativity of multiplication: $a \cdot (b \cdot c) = (a \cdot b) \cdot c$.
- Commutativity of addition: $a + b = b + a$.
- Additive identity element $0 \in F$: $a + 0 = a$. 
- Multiplicative identity element $1 \in F$: $a \cdot 1 = a$.
- Additive inverse of all elements $a$ is $-a$: $a + (-a) = 0$.
- Distributivity of multiplication over addition: $a \cdot (b + c) = (a \cdot b) + (a \cdot c)$.

In number theory, the binary multiplication operation is often commutative, in which case the set forms a /commutative ring/. If $a \cdot b = b \cdot a$, where $a$ and $b$ are elements of a ring $R$, the ring $R$ is a commutative ring and has the additional commutativity of multiplication axiom.

- Commutativity of multiplication: $a \cdot b = b \cdot a$.

Division is not defined in a ring in the same way division is defined in $\mathbb{R}$ or $\mathbb{Q}$. As is the case with a field, the subtraction operation can be defined using the additive inverse axiom.

\[a-b \stackrel{\text{def}}{=} a + (-b)\]

More often than not, rings are commutative and the word ring is used in place of commutative ring. The set of integers $\mathbb{Z}$ forms a commutative ring.

*** Commutative Semiring

A commutative semiring is an algebraic structure similar to a commutative ring, but without the requirement that each element of the carrier set has an additive inverse. A semiring is commutative if its multiplication is commutative.

- Associativity of addition: $a + (b + c) = (a + b) + c$.
- Associativity of multiplication: $a \cdot (b \cdot c) = (a \cdot b) \cdot c$.
- Commutativity of addition: $a + b = b + a$.
- Commutativity of multiplication: $a \cdot b = b \cdot a$.
- Additive identity element $0 \in F$: $a + 0 = a$. 
- Multiplicative identity element $1 \in F$: $a \cdot 1 = a$.
- Distributivity of multiplication over addition: $a \cdot (b + c) = (a \cdot b) + (a \cdot c)$.

The set of natural numbers $\mathbb{N}$ forms a commutative semiring.

*** Closure

A subset of a set is said to be /closed/ under an operation of the containing set if the result of the operation on a member of a subset always produces a member of that subset.

** Integer Numbers

The set of integers, denoted $\mathbb{Z}$ is the set of natural numbers, including zero and the set of negative number. The negative numbers are the additive inverses of the natural numbers. $\mathbb{N}$ is a subset of $\mathbb{Z}$. Each integer $a$ has an additive inverse such that $a+(-a) = 0$, therefore the set of integers forms a commutative ring, but not a field.

\[\{ \ldots , -3, -2, -1, 0, 1, 2, 3, \ldots \}\]

*** Mod & Div

The modulo operation, written $a \text{ mod } b$, returns the remainder of the division of $a$ by $b$. A modulo operation can be written $a = m \times b + r$, where $r < b$. The quotient $m$ is the result of the integer division function div.

\[ 356 \text{ mod } 100 = 56\]
\[ 356 \text{ div } 100 = 3\]
\[ 356 = 3 \times 100 +56\]

\[ 356 \text{ mod } 100 = 44\]
\[ 356 \text{ div } 100 = -4\]
\[ -356 = -4 \times 100 + 44\]

There are different implementations for =mod= and =div= operations on a computer. The quotient and remainder are signed for signed modulo operations. In number theory, floored division is preferred, the remainder has the same sign as the divisor, as in the examples given here. This is called =floorMod= or =floorDiv= in some languages.

*** Integer Notation

The positional notation used to write natural numbers needs to be extended to write the negative numbers in the set of integers.

The most simple system  is /Sign-magnitude/ notation. Negative numbers are prefixed with a minus sign, eg $-37$. Natural numbers can also be written with a distinct positive sign, eg $+37$. If the sign is omitted, the number is assumed to be positive. Inversion is very easy using this notation, changing the sign is the only step. In a computer system, an additional bit is required to store the sign, making the range of possible integer values with $n$ bits $(-2^{n-1} \ldotp \ldotp 2^{n-1})$, with both $+0$ and $-0$ being stored.

#+include: "./tables/sign_magnitude_notation.org"

/Complement/ notation makes integer arithmetic more practical at the cost of more complicated inversion. Writing a number in complement notation is effected by subtracting the absolute or positive value from 0. The inversion process is consistent in all bases. For any radix base $b$, the complement of a number can be calculated quickly by taking each digit's complement with $b-1$ and then adding $1$ to the value.

#+include: "./tables/complement_example.org"

In the case of this decimal number, its complement begins with the repeated digit $9$, which can be written $\dot 9$, a positive number in the same system begins with $\dot 0$. For any base $b$, a positive number begins $\dot 0 \ldots$  and a negative number begins $\dot {(b-1)} \ldots$. So $+282$ and $-282$ in sign-magnitude notation can be written $\dot 0 282$ and $\dot 9718$ in complement notation.

Two's complement is used to store negative integers in binary. The most significant bit in a word is signed. Numbers beginning $\dot 1 \ldots$ therefore include a negative value and are negative. Two's complement notation includes the additional value $-2^{n-1}$, instead of $-0$ making the range of integers that can be expressed with $n$ bits $[-2^{n-1} \ldotp \ldotp 2^{n-1})$.

#+include: "./tables/complement_notation.org"

*** Integer Intervals

An integer interval is a set of consecutive integers, which can be written compactly by defining its endpoints. $[$, $]$ are used to show inclusion and $($, $)$ are used for exclusion by convention.

- $[-3 \ldotp \ldotp 2]$ is the set of integers $n$ such that $-3 \le n \le 2$
- $[-3 \ldotp \ldotp 2)$ is the set of integers $n$ such that $-3 \le n < 2$
- $(-3 \ldotp \ldotp 2]$ is the set of integers $n$ such that $-3 < n \le 2$
- $(-3 \ldotp \ldotp 2)$ is the set of integers $n$ such that $-3 < n < 2$
- $[4 \ldotp \ldotp 4)$ is the empty set of integers $n$ such that $4 \le n < 4$
- $[10 \ldotp \ldotp \infty)$ is the infinite set of integers $n$ such that $10 \le n < \infty$
- $\mathbb{Z}$ is the interval $(- \infty \ldotp \ldotp \infty)$
- $\mathbb{N}$ is the interval $[0 \ldotp \ldotp \infty)$

*** Integer Lists

For a list of numbers, which the set of integers are sufficient to demonstrate, the sum and product of a list $L$ are written $\sum L$ and $\prod L$ respectively.

- $\sum [2,6,9] = 17$
- $\prod [2,6,9] = 108$
- $\sum [4,3,5,7,0] = 19$
- $\prod [4,3,5,7,0] = 0$
- $\sum [] = 0$
- $\prod [] = 1$

** Rational Numbers

A rational number is one which can be represented as a quotient of fraction of two integers $m$ and $n$ where $n \neq 0$, as in $m/n$ or $\frac{m}{n}$. The set of rational numbers has the symbol $\mathbb{Q}$. Every rational number can be written in a unique /irreducible/ form by requiring that $m$ and $n$ are coprime, this is sometimes called a rational number's canonical form. Two integers are coprime if their highest common divisor or factor is $1$. Every non-zero rational number has a multiplicative inverse, making $\mathbb{Q}$ a field.

** Real Numbers

The set of real numbers $\mathbb{R}$ is the set of continuous values, with arbitrarily small divisions. The real numbers include all of the rational numbers and other /irrational/ quantities, such as $\pi$ and $\sqrt{2}$. Real interval are written with a comma, while square and round brackets retain the same meaning as integer interval notation.

- $[-3 , 2]$ is the set of real numbers $n$ such that $-3 \le n \le 2$
- $[-3 , 2)$ is the set of real numbers $n$ such that $-3 \le n < 2$
- $(-3 , 2]$ is the set of real numbers $n$ such that $-3 < n \le 2$
- $(-3 , 2)$ is the set of real numbers $n$ such that $-3 < n < 2$
- $[4 , 4)$ is the empty set of real numbers $n$ such that $4 \le n < 4$
- $[10 , \infty)$ is the infinite set of integers $n$ such that $10 \le n < \infty$
- $\mathbb{R}$ is the interval $(- \infty \ldotp \ldotp \infty)$

** Floor & Ceiling 

Floor is the function which returns the greatest integer less than or equal to a real $a$, written $\lfloor a \rfloor$. Ceiling is the function which returns the smallest integer greater than or equal to a real $a$, written $\lceil a \rceil$.

- $\lfloor 8.4 \rfloor = 8$
- $\lceil 8.4 \rceil = 9$
- $\lfloor -6.2 \rfloor = -7$
- $\lceil -6.2 \rceil = -6$

** Modular Arithmetic

Two integers $a$ and $b$ are /congruent modulo/ $n$ if $n>0$ and the difference of $a$ and $b$ is a multiple of the modulus $n$; there exists an integer $k$ such that $a - b = kn$.

\[a \equiv b \text{ }(\text{mod } n)\]

In the definition of congruence mod $n$, the brackets means the mod operation applies to both left and right hand side, it is not just the modulo of $b$ by divisor $n$. If two numbers are congruent modulo $n$ they have a common remainder $r$ when divided by $n$.

\[a = pn + r\]
\[b = qn + r\]

If $a \equiv x \text{ }(\text{mod } n)$ and $b \equiv y \text{ }(\text{mod } n)$:

\[a + b \equiv x+y\text{ }(\text{mod } n)\]
\[a - b \equiv x-y\text{ }(\text{mod } n)\]
\[a \times b \equiv x \times y\text{ }(\text{mod } n)\]

*** Rings of Modular Arithmetic

Congruence modulo $n$ is an equivalence relation and an integer $a$ has the equivalence class $\overline{a}_n$, known as the /congruence class/ or /residue class/, all the numbers which have the same remainder when divided by $n$. The set of all residue classes of the integers modulo $n$, $\mathbb{Z}_n$ or $\mathbb{Z}/n\mathbb{Z}$ is know as the /least residue system/ and defined to be:

\[\mathbb{Z}_n = \{a \text{ mod } n \text{ }| \text{ } a \in \mathbb{Z}\} = \{0, \ldots, n-1\}\]

For integers in this set some functions can be defined:

\[a +_{n} b \stackrel{\text{def}}{=} (a+b) \text{ mod } n\]
\[a -_{n} b \stackrel{\text{def}}{=} (a-b) \text{ mod } n\]
\[a \times_{n} b \stackrel{\text{def}}{=} (a \times b) \text{ mod } n\]

$\mathbb{Z}$ is linked to $\mathbb{Z}_n$:

\[(a + b) \text{ mod } n = (a \text{ mod } n) +_{n} (b \text{ mod } n)\]
\[(a - b) \text{ mod } n = (a \text{ mod } n) -_{n} (b \text{ mod } n)\]
\[(a \times b) \text{ mod } n = (a \text{ mod } n) \times_{n} (b \text{ mod } n)\]

*** Fields of Modular Arithmetic

An element $a$ of $\mathbb{Z}_n$ has a multiplicative inverse if and only if $a$ is coprime with $n$. If $n$ is prime then all the elements of $\mathbb{Z}_n$ are coprime with $n$ and have a multiplicative inverse. $\mathbb{Z}_n$ forms a field when $n$ is prime.

* Set Theory

A /set/ is a collection of different items; a set contains /elements/. A set can be simply expressed by enumerating its elements, typically inside $\{$,$\}$ curly brackets. $\{2,4,6,8\}$ and
$\{\text{Alex}, \text{Benjamin}, \text{Richard}, \text{Bethan}\}$ are examples of sets.

** Membership & Equality

The symbol $\in$ denotes set membership, so if $x$ is a member of set $A$ this can be written $x \in A$. The notation $x \notin A$ means that $x$ is not an element of $A$. Two sets are equal when they contain the same elements, formally:

\[ A = B \iff (\forall x.x \in A \iff x \in B)\]

** Subsets

A set $B$ is a /subset/ of another set $A$, written $B \subseteq A$, if all the elements of $B$ are also elements of $A$.

\[ B \subseteq A \iff (\forall x.x \in B \implies x \in A)\]

Any set is a subset of itself $A \subseteq A$. If $B \subseteq A$ and $A \neq B$, then $B$ is a /proper subset/ of $A$, written $B \subset A$.

\[ B \subset A \iff (\forall x.x \in B \implies x \in A) \land \neg (A = B)\]

Two sets are equal if and only if they are subsets of each other.

\[ A = B \iff (A \subseteq B \land B \subseteq A)\]

** Set Operations

Some common set operations:

- $A \cup B$ is the /union/ of two sets, containing all the elements occurring in $A$ or $B$ or both.
- $A \cap B$ is the /intersection/ of two sets, containing all the elements occurring in both $A$ and $B$.
- $A \setminus B$ is the /difference/ of two sets, containing all the elements occurring in $B$ but not $A$.

** Set Cardinality

 Every finite set $A$ has a natural number /cardinality/ $|A|$, its size or number of elements. The empty set is written $\emptyset$ or $\{\}$ and has a cardinality of $0$. $\{\emptyset\}$ is not the empty set, as $1 \neq \{1\}$ it is the /singleton/ set, with cardinality $1$. 

** Set Builder Notation

Enumeration of a subset's elements is inconvenient for large subsets. A subset can be constructing concisely by selecting items from another set according to logical conditions in /set-builder notation/. The $|$ symbol is read /"such that"/.

\[\{n \in \mathbb{N} \text{ } |  \text{ }n \ge 10\} = \{10, 11, 12, \ldots\}\]
\[\{n^2 \text{ } |  \text{ } n\in \mathbb{N}, n^3 \ge 8\} = \{4, 9, 25, \ldots\}\]

** Product of Sets

A /tuple/ is a finite, ordered sequence of elements. An /ordered pair/ is a /2-tuple/, while an /ordered triple/ is a /3-tuple/, in general an /n-tuple/ has $n$ elements. The ordered pair $(a, b)$ does not equal $(b,a)$ unless $a=b$; order matters surprisingly. The product of two sets is the set of all ordered pairs.

\[A \times B \stackrel{\text{def}}{=} \{(x,y) | x \in A, y \in B\}\]

Every lists of sets has a product. The product of $\emptyset$ is $\{()\}$.

\[A \times B \times C \stackrel{\text{def}}{=} \{(x,y,z) | x \in A, y \in B, z \in C\}\]

** Special Sets

- $A^\ast$ is the set of all (finite) lists of elements of $A$.
- $A ^\omega$ is the set of all /streams/ (infinite sequences) of elements of $A$.
- $\mathcal{P}A$ is the /powerset/ (set of all subsets) of $A$.

** Subset Algebra

For any set $S$, $\mathcal{P}S$ is the set of all subsets of $S$. If $A$ and $B$ are elements of $\mathcal{P}S$ they are both subsets of $S$, called the common or /ambient/ set. Operations on $A$ and $B$ include $A \cup B$ and $A \cap B$ and also the /complement/ of $A$ relative to $S$, written $\overline{A}$.

\[\overline{A} \stackrel{\text{def}}{=} S \setminus A\]

The axioms that these operations have:

- Identity elements: $A \cup \emptyset = A$, $A \cap S = A$
- Absorbing elements: $A \cup S = S$, $A\cap \emptyset = \emptyset$ 
- Commutativity: $A \cup B$, $A \cap B$
- Associativity: $A \cup (B \cup C) = (A \cup B) \cup C$, $A \cap (B \cap C) = (A \cap B) \cap C$
- Idempotence: $A \cup A = A$, $B \cap B = B$
- Absorption: $(A \cup B) \cap B = B$, $(A \cap B) \cup B = B$
- Distributivity: $A \cap (B \cup C) = (A \cap B) \cup (A \cap C)$
- Distributivity: $A \cup (B \cap C) = (A \cap B) \cup (A \cap C)$
- Complements: $\overline{A} \cup A = S$, $\overline{A} \cap A = \emptyset$

Any set equipped with the operations $\land$, $\lor$, $\neg$ and two constants $\top$ and $\bot$ forms a boolean algebra. Every power set forms a boolean algebra assigning $\emptyset = \bot$ and the ambient set $S = \top$.

- Identity elements: $A \lor \bot = A$, $A \land \top = A$
- Absorbing elements: $A \lor \top = \top$, $A\land \bot = \bot$
- Commutativity: $A \lor B$, $A \land B$
- Associativity: $A \lor (B \lor C) = (A \lor B) \lor C$, $A \land (B \land C) = (A \land B) \land C$
- Idempotence: $A \lor A = A$, $B \land B = B$
- Absorption: $(A \lor B) \land B = B$, $(A \land B) \lor B = B$
- Distributivity: $A \land (B \lor C) = (A \land B) \lor (A \land C)$
- Distributivity: $A \lor (B \land C) = (A \land B) \lor (A \land C)$
- Complements: $\overline{A} \lor A = \top$, $\overline{A} \land A = \bot$

** Relations

If $A_1, A_2, \ldots, A_n$ is a list of $n$ sets and $R$ is a subset of $A_1 \times A_2 \times \ldots \times A_n$, then $R$ is a /n-ary Relation/. Elements of $A_1 \times A_2 \times \ldots \times A_n$ are all /n-tuples/. Any subset $R$ is a relation. A relation can be represented as a set of ordered /n-tuples/ in tabular or graphical form or using set-builder notation.

*** Binary Relations

A binary relation associates elements of one set, the /domain/, to another set, the /codomain/. A binary relation over the sets $X$ and $Y$ is a subset of $\mathcal{P}(X \times Y)$. A binary relation is /homogeneous/ when $X = Y$ and is said to be a binary relation over $X$. $(x, y) \in R$ means that $x$ is related to $y$, sometimes written $xRy$. A binary relation is a generalisation of a /unary/ function which maps one input to one output.

The composition of the relation $R \subseteq A \times B$ and $S \subseteq B \times C$ is written $S \circ R \subseteq = A \times C$; $R$ is applied first and then $S$.

\[S \circ R = \{(a,c) \text{ } | \text{ } \exists b \in B. (a,b) \in R \land (b,c) \in S \}\]

If $R \subseteq A \times B$, then $R^\circ \subseteq B \times A$. $R^\circ$, $R^{-1}$ or $R^T$ is called the /converse/, /inverse/ or /transpose/ relation of $R$.

\[yR^\circ x \iff xRy\]
\[R^\circ = \{(y, x) \in B \times A | (x, y) \in R\}\]

*** Functions

A function is a type of binary relation which maps every element of the domain to exactly one element of the codomain. For a relation $R \subseteq A \times B$, $R$ must satisfy two conditions if it is a /functional relation/.

1. *Total:* For every element $a \in A$, there must exist an ordered pair in $R$ where $a$ is the first element.

   \[\forall a \in A \exists b \in B . (a, b) \in R\]

2. *Single-valued:* For every element $a \in A$, there is only one value $b \in B$ such that $(a,b) \in R$. There is only one output for each element in the domain.

   \[\forall a \in A \forall b,c \in B. (a,b) \in R \land (a,c) \in R \implies b=c\]

If $f \subseteq A \times B$ is a function or /functional relation/, its /domain/ is $A$ and its /co-domain/ is $B$. The set of all possible outcomes of a function is a subset of its co-domain, called the /range/ of $f$.

\[\{b \in B \text{ } | \text{ } \exists a\in A. (a,b) \in f\}\]

A relation is not a function if there exists an element in the domain which has multiple values in the co-domain, or if any of the elements in the domain have no value in the co-domain, as in figure [[fig:not_functional_relation]]

#+CAPTION: Two non-functional relations
#+ATTR_LATEX: :placement [H] :scale 1
#+NAME: fig:not_functional_relation
[[./res/invalid_functions.svg]]

Instead of using the notation $f \subseteq A \times B$ to write the domain and co-domain of a functional relation the notation $f: A \mapsto B$ is preferred. Instead of writing $(a, b) \in f$, the notation $f(a) = b$ is used to say $a$ maps to $b$.

If $f : A \mapsto B$, $b \in B$ is the /image/ of *element* $a \in A$, and $a$ is the /pre-image/ of $b$. The term /image/ may also refer to a subset $X$ of the domain $A$, in which case the /image/ is the set of outputs of $f$ applied to elements of $X$, written $f[X]$. Using this notation the /image/ of the whole domain, the range of $f$, is written $f[A]$ ($A \subseteq A$).

\[f[X] \stackrel{\text{def}}{=} \{b \in B \text{ } | \text{ } \exists x \in X. f(x) = b \}\]

The /reverse image/ of a subset $Y$ of the co-domain is denoted $f^{-1}[Y]$

\[f^{-1}[Y] \stackrel{\text{def}}{=} \{a \in A\text{ } | \text{ } f(a) \in Y\}\]

There are several different properties a function may satisfy, illustrated in figure [[fig:functional_relations]].

#+CAPTION: Set of valid functions
#+ATTR_LATEX: :placement [H] :scale 1
#+NAME: fig:functional_relations
[[./res/functions.svg]]

1. General function: defined and single-valued for each element of A. The /many-to-one/ property is valid for a general function. There may be elements of the co-domain without a pre-image in $A$. 
2. Injective (not surjective) function: no two elements of $B$ have the same pre-image in $A$, a form of /one-to-one/ function; no two elements of $A$ share the same image.

   \[\forall x,y \in A.x \neq y \implies f(x) \neq f(y)\]
   \[\forall x,y \in A.f(x) = f(y) \implies x=y\]

3. Surjective (not injective) function: the range of the function is the entire co-domain. Every element of $B$ has a pre-image in $A$. If a function is surjective, the cardinality of $A$ is less than or equal to the cardinality of $B$, $|A| \le |B|$.

   \[\forall b\in B \exists a \in A. f(a) = b\]

4. Bijective function: both injective and surjective, the domain and co-domain have equal cardinality $|A| = |B|$.

*** Endorelations

A binary relation $R$ from a set $A$ to itself is called an /endorelation/ on $A$, $R \subseteq A \times A$. A function from $A$ to $A$ is called an /endofunction/. A binary relation may have some additional special properties.

- *Reflexivity:* A binary relation is /reflexive/ if every element of the set is related to itself.

  \[\forall x \in A. (x,x) \in R\]

- *Irreflexivity:* A binary relation is /irreflexive/ if every element of the set is not related to itself.

  \[\forall x \in A. (x,x) \notin R\]

- *Symmetry:* A binary relation is /symmetric/ if for all elements $x$ and $y$ in $A$ if $x$ is related to $y$ then $y$ is related to $x$.

  \[\forall x,y \in A. (x,y) \in R \implies (y,x) \in R\]

- *Antisymmetry:* A binary relation is /antisymmetric/ if for all elements $x$ and $y$ in $A$ if $x$ is related to $y$ then $x = y$.

  \[\forall x,y \in A. (x,y) \in R \land (y,x) \in R \implies y = x\]

- *Asymmetry:* A binary relation is /asymmetric/ if it is both antisymmetric and irreflexive.

  \[\forall x,y \in A . (x,y) \in R \implies (y,x) \notin R\]

- *Transitive:* A binary relation is /transitive/ if for all elements $x$, $y$ and $z$ in $A$ if $x$ is related to $y$ and $y$ is related to $z$, then $x$ is related to $z$.

  \[\forall x,y,z \in A. (x,y) \in R \land (y,z) \in R\implies (x,z) \in R\]

*** Equivalence Relation

An /equivalence relation/ is /reflexive/, /symmetric/ and /transitive/. The symbols $\approx$ and $\equiv$ are often used to denote equivalence relations. If a set $A$ is equipped with an equivalence relation, every element of $A$ has an /equivalence class/, the set of elements equivalent to it. The equivalence class of $x$ is written $[x]_\equiv$.

\[[x]_\equiv \stackrel{\text{def}}{=} \{y \in A \text{ }| \text { } x \equiv y\}\]

An element always belongs to the equivalence class containing itself $x \in [x]_\equiv$. If $x \equiv y$ then $[x]_\equiv =[y]_\equiv$. If $x \not\equiv y$ then $[x]_\equiv \cap [y]_\equiv = \emptyset$, any two equivalence classes are fully disjoint. 

An equivalence relation forms a /classification/ of elements of $A$; $A$ is decomposed into subsets. The set of all equivalence classes is $A/\equiv$. These classes are all disjoint, no element can be in more than one equivalence class and each element is in some equivalence class, the set $A$ is fully covered by $A/ \equiv$.

For a function $f: A \mapsto B$, which is not injective, its /kernel/ is the equivalence relation on $A$ which relates two elements with the same image in $B$ under $f$, written $\text{ker}(f)$. Therefore the set of equivalence classes $A / \text{ker}(f)$ corresponds to the range of $f$.

* Linear Algebra
** Gaussian Elimination

Gaussian elimination is a technique for solving a system of linear equations with $n$ equations and $n$ variables, using the /matrix of coefficients/ and the elementary row operations:

1. Rearrange two rows.
2. Multiply a row by a scalar.
3. Add two rows.

/Row echelon form/ has the first non-zero element of each row in the main diagonal and 0 coefficients below the main diagonal. This form gives one coefficient directly and makes back substitution easy.

\[\left[\begin{array}{ccc|c}1&\ast&\ast&\ast \\ 0&1&\ast&\ast \\ 0&0&1&\ast \end{array} \right ]\]

Sometimes /reduced row echelon form/ is preferred for reading coefficients more easily.

\[\left[\begin{array}{ccc|c}1&0&0&\ast \\ 0&1&0&\ast \\ 0&0&1&\ast \end{array} \right ]\]

** Vector Spaces

A /vector space/ over a field $F$ is a set $V$ equipped with two binary operations: vector addition and scalar multiplication. Any element of $V$ is a vector, regardless of its form (assuming the conditions for a vector space are upheld). Vector addition assigns two vectors $\vec{v}$ and $\vec{w}$ in $V$ to a third vector $\vec{v} + \vec{w}$ in $V$, otherwise written $\vec{v} \oplus\vec{w}$. Scalar multiplication assigns a vector $\vec{v} \in V$ and a scalar $s \in F$ to a vector $s \vec{v}$. Sometimes $\boldsymbol{v}$, $\boldsymbol{w}$ notation is used in place of $\vec{v}$ and $\vec{w}$ to distinguish vectors from scalars. Vector spaces uphold some axioms.

- Associativity of vector addition: $\vec{u} \oplus (\vec{v} \oplus \vec{w}) = (\vec{u} \oplus \vec{v}) \oplus \vec{w}$.
- Commutativity of vector addition: $\vec{u} \oplus \vec{v} = \vec{v} \oplus \vec{u}$.
- Identity element of vector addition $\boldsymbol{0} \in V$: $\vec{v} \oplus \boldsymbol{0} = \vec{v}$. 
- Additive inverse of vector addition $-\vec{v} \in V$: $\vec{v} \oplus -(\vec{v}) = 0$.
- Associativity of scalar & vector multiplication: $r(s\vec{v}) = (rs)\vec{v}$
- Identity element of scalar multiplication $1 \in F$: $1\vec{v} = \vec{v}$
- Distributivity of scalar multiplication: $(r+s)\vec{v} = r\vec{v} \oplus s\vec{v}$
- Distributivity of scalar multiplication: $s(\vec{v} + \vec{w}) = s\vec{v} \oplus s\vec{w}$

Some derived statements about vector spaces:

- $\vec{v} - \vec{w} = \vec{v} \oplus (-\vec{w})$
- $0\vec{v} = \boldsymbol{0}$
- $s\boldsymbol{0} = \boldsymbol{0}$
- $(-1)\vec{v} = -\vec{v}$
- $s\vec{v} = \boldsymbol 0 \implies s = 0 \lor \vec{v} = \boldsymbol{0}$

*** Examples

Every field is a vector space over itself. Fields are closed under $+$ and $\times$, thus $\oplus$ can be defined as $+$ and scalar multiplication is simply $\times$. The set of /n/-tuples of rational numbers $\mathbb{Q}$ is a vector space over $\mathbb{Q}$.

\[\mathbb{Q}^n \stackrel{\text{def}}{=} \{(a_1, \ldots, a_n) \text{ } | \text{ } a_1, \ldots a_n \in \mathbb{Q}\}\]

An /n/-tuple is sometimes written vertically if it is an element of a vector space.

\[(a_1, \ldots, a_n) = \begin{pmatrix} a_1\\ \vdots \\a_n \end{pmatrix}\]

For any /n/-tuple, vector addition and scalar multiplication are defined:

\[\begin{pmatrix} a_1\\ \vdots \\a_n \end{pmatrix} \oplus \begin{pmatrix} b_1\\ \vdots \\b_n \end{pmatrix} \stackrel{\text{def}}{=} \begin{pmatrix} a_1 & + & b_1\\ \vdots & + & \vdots \\a_n & + & b_n \end{pmatrix}\]

\[s\begin{pmatrix} b_1\\ \vdots \\b_n \end{pmatrix} \stackrel{\text{def}}{=} \begin{pmatrix} s \times a_1\\ \vdots \\ s \times a_n \end{pmatrix}\]

*** Span

The span of two vectors $\vec{v}$ and $\vec{w}$ is the set of all possible linear combinations of $\vec{v}$ and $\vec{w}$.

\[\text{Span}(\vec{v}, \vec{w})\stackrel{\text{def}}{=} \{r\vec{v} \oplus s\vec{w} \text{ } | \text{ } r,s \in F\}\]

Any set of vectors has a span:

\[\text{Span}(\vec{v}_1, \ldots, \vec{v}_n)\stackrel{\text{def}}{=} \{r_1\vec{v}_1 \oplus \ldots \oplus r_n\vec{v}_n \text{ } | \text{ } r_1, \ldots ,r_n \in F\}\]

A vector belongs to the span of a set of vectors $\{\vec{v}_1, \ldots, \vec{v}_n\}$, if it can be written as a linear combination of the set of vectors. If the span of a set of vectors is all of $V$, every element of $V$ is a linear combination of $\{\vec{v}_1, \ldots, \vec{v}_n\}$, it is a /spanning set/.

*** Linear Independence

A set of vectors $\{\vec{v}_1, \ldots, \vec{v}_n\}$ is /linearly independent/ if $r_1\vec{v}_1 \oplus \ldots \oplus r_n\vec{v}_n = \vec{0} \implies r_1 = \ldots = r_n = 0$. The only way to obtain the zero vector $\vec{0}$ is by taking each scalar to be $0$.

*** Basis

A set of vectors $\vec{v}_1, \ldots, \vec{v}_n \in V$ forms a /basis/ if $\text{Span}(\vec{v}_1, \ldots, \vec{v}_n) = V$ and $\{\vec{v}_1, \ldots, \vec{v}_n\}$ is linearly independent. The inner product of two /n/-tuple vectors is defined to be:

\[\vec{v} \cdot \vec{w} \stackrel{\text{def}}{=} (v_1 \times w_1) + \ldots + (v_n \times w_n)\]

A basis set of vectors $B$ is /orthogonal/ if the inner product of all elements of $B$ with each other is $0$.

** Matrices

A matrix is a two-dimensional array of values from a field. Matrices can be read row-wise or column-wise. The size of a matrix is $m \times n$ where $m$ is the number of rows and $n$ is the number of columns. The notation $a_{ij}$ means the element in row $i$ and column $j$.

\[A_{2\times 3 } = \begin{bmatrix} a_{11} & a_{12} & a_{13} \\ a_{21} & a_{22} & a_{23}\end{bmatrix}\]

*** Matrix Multiplication

Matrix multiplication is defined for two matrices $A_{m \times n}$ and $B_{n \times p}$, the number of rows in $B$ must equal the number of columns in $A$. Elements of $A$ are given by $a_{ij}$ and elements of $B$ are given by $b_{jk}$ The result is a $m \times p$ matrix, whose element in row $i$ and column $k$ is the inner product of row $i$ of $A$ and column $k$ of $b$.

\[c_{ik} = \sum_{j=1}^{n} a_{ij} \times b_{jk} \]

Matrix multiplication is associative but not commutative.

*** Matrix Inversion

The inverse of a matrix $A$ is $A^{-1}$, such that $AA^{-1} = I$, where $I$ is the identity matrix. Not all matrices have an inverse. The identity matrix is a square matrix and has 1 in the main diagonal and 0 everywhere else. $I_2, I_3, I_4$:

\[\left [ \begin{array}{cc} 1&0 \\ 0&1\end{array} \right ] \left [ \begin{array}{ccc} 1&0&0 \\ 0&1&0 \\ 0&0&1\end{array} \right ] \left [ \begin{array}{cccc} 1&0&0&0 \\ 0&1&0&0 \\ 0&0&1&0 \\ 0&0&0&1\end{array} \right]\]

To calculate the inverse for a matrix, write $[A|I]$ and perform elementary row operations to write $A$ as the identity matrix, which will arrange $I$ into $A^{-1}$.

\[\left[\begin{array}{ccc|ccc} \ast&\ast&\ast&1&0&0\\ \ast&\ast&\ast&0&1&0\\ \ast&\ast&\ast&0&0&1\\\end{array} \right ] \rightarrow \left[\begin{array}{ccc|ccc} 1&0&0&\ast&\ast&\ast\\ 0&1&0&\ast&\ast&\ast\\ 0&0&1&\ast&\ast&\ast\\\end{array} \right ]\]
